[project]
name = "seleksi-2025-tugas-1"
version = "0.1.0"
description = "Database Lab Assistant 2025 Recruitment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pandas>=2.3.1",
]
